name = "url-shortener"
compatibility_date = "2024-04-11"
workers_dev = false
main = "src/index.ts"

kv_namespaces = [
  { binding = "URL_MAPPINGS", id = "3ace05f2a9474b9090dd68d8a35c3597" },
  { binding = "URL_ANALYTICS", id = "60215ddbff6f42e4a33375bb1109a2b7" },
  { binding = "API_KEYS", id = "329889d1e0c74a6ca596662e2f52a312" },
  { binding = "OG_METADATA_CACHE", id = "c900ebf80a9a4a3a894aaf04b38e800b" }
]

[vars]
REDIRECT_URL = ""
ALLOWED_CORS_ORIGINS = ""

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

# [[d1_databases]]
# binding = "DB"
# database_name = "my-database"
# database_id = ""

# [ai]
# binding = "AI"
